Improve check-versions script

diff --git a/scripts/list-versions b/scripts/list-versions
--- a/scripts/list-versions
+++ b/scripts/list-versions
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 set -e -u
 
-: "${TERMUX_HOST_PLATFORM:="aarch64"}"
+TERMUX_HOST_PLATFORM=aarch64
 TERMUX_ARCH_BITS=64
 TERMUX_PKG_SRCDIR=/tmp/termux-src
 TERMUX_PKG_HOSTBUILD_DIR=/tmp/termux-hostbuild-dir
@@ -15,9 +15,30 @@ TERMUX_PKG_API_LEVEL=28
 TERMUX_PYTHON_VERSION=3.11
 TERMUX_BUILD_TUPLE=x86_64-pc-linux-gnu
 TERMUX_PYTHON_HOME=/tmp/termux-python-home
-
 TERMUX_SCRIPTDIR=$(dirname "$(realpath "$0")")/..
 TERMUX_ON_DEVICE_BUILD=false
+
+_show_usage() {
+> echo "Usage: $0 [-a ARCH]"
+> echo "List versions of local package definitions."
+> echo "  -a The architecture to build for: aarch64(default) or x86_64"
+> exit 1
+}
+
+while getopts :a:hdio: option; do
+	case "$option" in
+		a) TERMUX_HOST_PLATFORM="$OPTARG";;
+		h) _show_usage;;
+		*) _show_usage >&2 ;;
+	esac
+done
+shift $((OPTIND-1))
+if [ "$#" -ne 0 ]; then _show_usage; fi
+if [[ ! "$TERMUX_HOST_PLATFORM" =~ ^(aarch64|x86_64)$ ]]; then
+	echo "ERROR: Invalid arch '$TERMUX_ARCH'" 1>&2
+	exit 1
+fi
+
 . "$TERMUX_SCRIPTDIR"/scripts/properties.sh
 
 check_package() { # path
@@ -37,12 +58,13 @@ check_package() { # path
 		TERMUX_PKG_VERSION+="-$TERMUX_PKG_REVISION"
 	fi
 	echo "$pkg=$TERMUX_PKG_VERSION"
+
 	local subpkg_file
 	for subpkg_file in "$path"/*.subpackage.sh; do
 		if [ -f $subpkg_file ]; then
 			local subpkg_name=$(basename $subpkg_file)
 			local subpkg_name=${subpkg_name%.subpackage.sh}
-			echo $subpkg_name=$TERMUX_PKG_VERSION
+			echo "${subpkg_name}<-${pkg}=$TERMUX_PKG_VERSION"
 		fi
 	done
 }
